apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      tier: app
  template:
    metadata:
      labels:
        tier: app
    spec:
      containers:
        - name: nodejs

          image: macarious25siv/project:9b26f2113cfa9e284702779aee5677a9f8193b19
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_URI
              value: "mongodb://db-service.default.svc.cluster.local:27017/test"
            - name: MONGODB_USERNAME
              value: "testuser"
            - name: MONGODB_PASSWORD
              value: "testpassword"


---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    tier: app
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      nodePort: 30333
